export const POST_CARD_ITEM_MOCK = [
  {
    id: '1',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '2',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '3',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '4',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '5',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '6',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '7',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
  {
    id: '8',
    title: 'Post Title',
    description: 'This is a description of the post.',
    tags: ['tag1', 'tag2', 'tag3'],
    date: '2026.10.10',
    imageUrl: '/path/to/image.jpg',
  },
];
